// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD55Jo658b1po-t5Nq1ep8fKIlvT3J4zVY',
    appId: '1:738480845733:web:c747dc61af872165dd2e4c',
    messagingSenderId: '738480845733',
    projectId: 'nostracode-003-fb233',
    authDomain: 'nostracode-003-fb233.firebaseapp.com',
    storageBucket: 'nostracode-003-fb233.appspot.com',
    measurementId: 'G-Z1S25CFRW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADzo_5vTkWGFurkRS40lxTqJg3ucZ1msM',
    appId: '1:738480845733:android:946ae5b6b00bb0ccdd2e4c',
    messagingSenderId: '738480845733',
    projectId: 'nostracode-003-fb233',
    storageBucket: 'nostracode-003-fb233.appspot.com',
  );
}
