// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDza53QPUsIW0hMRDZrhs-1uUh5Lgio9f8',
    appId: '1:615117587258:web:bcdbc98e9bd5414af30603',
    messagingSenderId: '615117587258',
    projectId: 'nostracode-003',
    authDomain: 'nostracode-003.firebaseapp.com',
    storageBucket: 'nostracode-003.appspot.com',
    measurementId: 'G-9EV3K1XSW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA07tateddrYGYAFgBIlw6i1YhZIeb73pk',
    appId: '1:615117587258:android:86ee0ce6cd9ad187f30603',
    messagingSenderId: '615117587258',
    projectId: 'nostracode-003',
    storageBucket: 'nostracode-003.appspot.com',
  );
}
