// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxJCJ3gp4v8heArErW4T8SpAE5e6174hg',
    appId: '1:945397266986:web:832e574cf608a64644a153',
    messagingSenderId: '945397266986',
    projectId: 'nostracode-003z',
    authDomain: 'nostracode-003z.firebaseapp.com',
    storageBucket: 'nostracode-003z.appspot.com',
    measurementId: 'G-J3XQP4NRSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJx93XZLGL_Gzmei7EiNopaIiEvvpBoNo',
    appId: '1:945397266986:android:f186e30b4ad1877144a153',
    messagingSenderId: '945397266986',
    projectId: 'nostracode-003z',
    storageBucket: 'nostracode-003z.appspot.com',
  );
}
